{% set name = "xgrads" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 430aecd995ad6804d2e9121c30b2dbc2d68a515f22d30f5e56a95e501ee49501

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - dask
    - numpy
    - pyproj
    - numba

test:
  imports:
    - xgrads
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/miniufo/xgrads
  summary: 'Parse and read ctl and associated binary file commonly used by GrADS into xarray'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://xgrads.readthedocs.io/
  dev_url: https://github.com/miniufo/xgrads

extra:
  recipe-maintainers:
    - miniufo
